### ISSUE TITLE
Change SpecificationError to a warning

### ISSUE THREAD

**Issue by rhetorica** [OmegaK2/PyPoE#103] opened 2019-12-13 19:31 UTC
This issue is on-going. First mentioned in bug 96: https://github.com/OmegaK2/PyPoE/issues/96

With the brand-new Metamorph content just released, and on the latest build of PyPoE running under Python 3.7 and Windows 7 x64, `pypoe_exporter dat json` fails with:

`PyPoE.poe.file.specification.errors.SpecificationError: <ERRORS.RUNTIME_ROWSIZE_MISMATCH: 3002>: "ActiveSkills.dat": Specification row size 101 vs real size 109`

**Comment by OmegaK2** [comment] 2019-12-13 23:37
Well yes that is too be expected, and otherwise it's a duplicate of the other issue.

**Closed as completed by OmegaK2** 2019-12-13 23:37 UTC
Labels: duplicate
